easy_admin:
    entities:
        Athlete:
            class: App\Entity\Athlete
            label: 'Licenciés'
            list:
                title: '%%entity_label%%'
        Ligue:
            class: App\Entity\Ligue
            label: 'Ligues'
            list:
                title: '%%entity_label%%'
        Team:
            class: App\Entity\Team
            label: 'Equipes'
            list:
                title: '%%entity_label%%'
        Race:
            class: App\Entity\Race
            label: 'Courses'
            list:
                title: '%%entity_label%%'
        Club:
            class: App\Entity\Club
            label: 'Clubs'
            list:
                title: '%%entity_label%%'
    site_name: Classement raid fftri
    design:
        brand_color: '#1ABC9C'
        assets:
            # all kinds of assets are supported and linked accordingly
            css:
                - 'bundles/easyadmin/bootstrap-all.css'
            js:
                - 'bundles/easyadmin/bootstrap-all.js'
