fos_user:
  firewall_name: main
  user_class: App\Entity\User
  db_driver: orm
  service:
    mailer: fos_user.mailer.twig_swift
  from_email:
      address: "%env(FROM_EMAIL)%"
      sender_name: "%env(FROM_EMAIL)%"
  registration:
      confirmation:
          enabled: true
      form:
          type: App\Form\RegistrationFormType