vich_uploader:
    db_driver: orm

    mappings:
        race:
            uri_prefix: "%app.path.ranking_files%"
            upload_destination: '%kernel.project_dir%/public%app.path.ranking_files%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true